import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className="ml-2">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-violet-500 text-2xl">Devkode: A frontend Community</h1>
      <span className="bg-green-500"> Community sharing Portal</span>
      
    </div>
  )
}
