import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useContext } from 'react'
import Navbar from '../Components/Navbar'
import Todo from '../Components/Todo'
import { TodosContext } from '../contexts/TodosContext'
import Auth0 from '@auth0/nextjs-auth0'
import { table, minifyRecords } from './api/utils/Airtable'

import { useUser } from '@auth0/nextjs-auth0';


const Home = ({ initialTodos }) =>
{
  const { todos, setTodos } = useContext(TodosContext)
  
  useEffect(() => {
    setTodos(initialTodos)
  }, [])

  console.log(`here ${ initialTodos }`)
  console.log(todos)

   const { user, error, isLoading } = useUser();

  // if (isLoading) return <div>Loading...</div>;
  // if (error) return <div>{error.message}</div>;

  if (user) {
   console.log(user)
  } else {
    console.log(`no user`)
 }
 

  // if (user) { }
    return (
      <div>
       <Head>
        <title>Authenticated To-do App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
     
      </Head>
      
        <Navbar/>
      <main >
        <h1 className="container mx-auto my-10">To do</h1>
          <ul>
            {user && <p>Hello {user.given_name}</p>}
         
        {todos && todos.map(todo =>(<Todo key={todo.id} todo={todo}/>))}
     
          </ul>
          </main>
      </div>
    );
  
  
//   return (
//     <div>
//       User logged out!
//       <a href="/api/auth/login">Login</a>
//       </div>);
  // 
}

export default Home;
//this function runs even before loading the above markup

export async function getServerSideProps(context)

{
  try {
    const todos = await table.select({}).firstPage()
    
  return {
    props: {
      initialTodos: minifyRecords(todos)
    }
  }
  } catch (err) {
    console.error(err.message)
  }
 
}